[
  {
    "proxy": "142.111.48.150:6927:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.26s",
    "note": "Test: www.instagram.com",
    "assigned_account": ""
  },
  {
    "proxy": "31.58.30.11:6593:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "2.95s",
    "note": "Test: www.instagram.com",
    "assigned_account": ""
  },
  {
    "proxy": "198.12.112.132:5143:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.59s",
    "note": "Test: www.instagram.com",
    "assigned_account": ""
  },
  {
    "proxy": "46.202.224.251:5803:wwipvaeh:tfjxibkjxots",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 402 Payment Required')))",
    "assigned_account": ""
  },
  {
    "proxy": "38.170.190.6:9357:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "4.05s",
    "note": "Test: www.instagram.com",
    "assigned_account": ""
  },
  {
    "proxy": "154.30.250.127:5639:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.41s",
    "note": "Test: www.instagram.com",
    "assigned_account": ""
  },
  {
    "proxy": "38.153.135.14:5394:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "7.72s",
    "note": "Test: www.instagram.com",
    "assigned_account": ""
  },
  {
    "proxy": "104.232.209.107:6065:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.18s",
    "note": "Test: www.instagram.com",
    "assigned_account": ""
  },
  {
    "proxy": "198.20.191.230:5300:wwipvaeh:tfjxibkjxots",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 402 Payment Required')))",
    "assigned_account": ""
  },
  {
    "proxy": "173.211.8.111:6223:wwipvaeh:tfjxibkjxots",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 402 Payment Required')))"
  },
  {
    "proxy": "46.202.224.251:5803:wwipvaeh:tfjxibkjxots",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 402 Payment Required')))"
  },
  {
    "proxy": "198.20.191.230:5300:wwipvaeh:tfjxibkjxots",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 402 Payment Required')))"
  },
  {
    "proxy": "38.153.140.182:9060:wwipvaeh:tfjxibkjxots",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 402 Payment Required')))"
  },
  {
    "proxy": "31.58.30.11:6593:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "2.93s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "38.170.190.6:9357:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "4.05s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "192.186.176.123:8173:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "4.20s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "154.30.250.127:5639:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.35s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "198.46.161.208:5258:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "2.82s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "142.111.48.150:6927:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "2.77s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "198.12.112.132:5143:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.42s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "38.153.135.14:5394:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.94s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "104.253.77.181:5603:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "2.94s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "104.232.209.107:6065:hfhaklgorb:hfhaklgorb",
    "type": "HTTP",
    "status": "Hoạt động",
    "speed": "3.41s",
    "note": "Test: www.instagram.com"
  },
  {
    "proxy": "124.243.141.205:25613",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBEC907D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25575",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8077390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25724",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8075950>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25728",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBEC90B90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25667",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBBB27ED0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25763",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8075090>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25999",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBEC90550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25885",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8582490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25858",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8075BD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25523",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8582AD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25647",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8074410>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25717",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBEC90050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25898",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DB8581590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25572",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBBB279D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25502",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBEC90910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25609",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBBB24CD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  },
  {
    "proxy": "124.243.141.205:25749",
    "type": "HTTP",
    "status": "Lỗi",
    "speed": "",
    "note": "HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011DBBB27C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"
  }
]